### ISSUE TITLE
Unit tests failing on Windows

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-cli-db2-plugin#74]
Some unit tests fail on Windows + Node.js 14 with this error:
```
    The specified module could not be found.
    \\?\C:\dev\zowe-cli-db2-plugin\node_modules\ibm_db\build\Release\odbc_bindings.node

      at Runtime._loadModule (node_modules/jest-runtime/build/index.js:572:29)
      at bindings (node_modules/bindings/bindings.js:112:48)
      at Object.<anonymous> (node_modules/ibm_db/lib/odbc.js:57:31)
```

Adding `zowe-cli-db2-plugin/node_modules/ibm_db/installer/clidriver/bin` to PATH fixes the issue (as suggested [here](https://github.com/ibmdb/node-ibm_db/issues/607#issuecomment-582263873)).

**Comment by zFernand0** [comment]
fixed by: fbe77079526cf9de239c23824d7585b13f3252c6
